## 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)

**컴파일 에러(compile-time error) :** 컴파일 할 때 발생하는 에러
**런타임 에러(runtime error) :** 프로그램의 실행도중에 발생하는 에러
**논리적 에러(logical error) :** 컴파일도 잘되고 실행도 잘되지만 의도한 것과 다르게 동작하는 것

**예외 처리(exception handling)** :  프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것
**예외처리의 목적 :** 예외의 발생으로 인한 실행 중인 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지할 수 있도록 하는 것

<aside>
💡 발생한 예외를 처리하지 못하면 프로그램은 비정상적으로 종료되며, 처리되지 못한 예외(uncaught exception)는 JVM의 **예외처리기(UncaughtExceptionHandler)**
가 받아서 예외의 원인을 출력

</aside>

### try-catch-finally

```java
public static void exception1(){
    try {
        // 예외가 발생할 수 있는 로직
    } catch (Exception e1) {
        // 예외시 처리할 코드
    } finally {
        // 예외와 상관없이 항상 실행할 코드
    }
}
```

try-catch문은 함께 쓰이며 finally는 선택하여 사용 가능

### throw, throws

```java
class App {
    public static void main(String[] args) {
        try {
            Exception e = new Exception("예외 발생");
            throw e;
        } catch (Exception e) {
            System.out.println("에러 메시지 : " + e.getMessage());
            e.printStackTrace();
        }
        System.out.println("프로그램 정상 종료");
    }
}
```

예외 클래스의 객체를 만들어 throw를 통해 예외를 발생 시킴

```java
public static void exception2() throws Exception {
    // 특정 조건 발생시
    throw new Exception();
}
```

본인이 원하는 조건을 걸어 놓고 그 조건 발생 시 throw문을 통해 Exception을 발생 시키는 방법

## 자바가 제공하는 예외 계층 구조

![Untitled](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/1c03d25f-179e-434b-91f1-6f63df53771a/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220922%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220922T080747Z&X-Amz-Expires=86400&X-Amz-Signature=aa21e6d5d7ed9c3bcce94d84337228ab9dbff145ca56a6daddcedd067742ee12&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)

사진 출처 : [https://blog.naver.com/eksqlrhdwb/221367734606](https://blog.naver.com/eksqlrhdwb/221367734606)

## Exception과 Error의 차이는?

**Exception :** 개발자가 구현한 로직에서 발생

**Error :** 시스템 레벨에서 발생하며 핸들링이 어려움 (메모리부족, 스택오버플로우와 같은 복구할 수 없는 수준의 오류)

**= 프로그램 코드에 의해서 수습이 될 수 있는지 없는지 차이**

## RuntimeException과 RE가 아닌 것의 차이는?

RuntimeException은 컴파일 단계에서 확인이 불가

Exception은 컴파일 단계에서 확인이 가능

## 커스텀한 예외 만드는 방법

```java
public class CustomException extends Exception {
    private final int ERR_CODE;

    //에러 메세지(커스텀)
    public CustomException(String message) {
        this(message,200);
    }

    // 에러 메세지(커스텀), 에러 코드(커스텀)
    public CustomException(String message, int ERR_CODE) {
        super(message);
        this.ERR_CODE = ERR_CODE;
    }

    // 에러코드 리턴
    public int getErrorCode() {
        return ERR_CODE;
    }
}
```

```java
public class CustomExceptionApp {
    public static void main(String[] args) {
        try{
            checkAge(2022);
        } catch (CustomException e){
            e.printStackTrace();
            System.out.println("ERR_MSG : "+ e.getMessage());
            System.out.println("ERR_CODE : "+ e.getErrorCode());
        }
    }

    private static void checkAge(int birthYear) throws CustomException {
        final int YEAR = 2021;

        //탄생년도가 2021년 보다 큰 경우
        if(YEAR - birthYear < 0)
            throw new CustomException("Too Big Birth Year");

        //탄생년도가 1800년 보다 작은 경우
        if(birthYear < 1800)
            throw new CustomException("Maybe Wrong Birth Year",100);
    }
}
```
---

**참고했습니다.**

[https://www.notion.so/cce3fc21976f4400aa4ed8d3fb26497b](https://www.notion.so/cce3fc21976f4400aa4ed8d3fb26497b)

[https://yadon079.github.io/2021/java study halle/week-09](https://yadon079.github.io/2021/java%20study%20halle/week-09)

[https://zayson.tistory.com/m/entry/백기선님과-함께하는-Live-Study-9주차-예외-처리](https://zayson.tistory.com/m/entry/%EB%B0%B1%EA%B8%B0%EC%84%A0%EB%8B%98%EA%B3%BC-%ED%95%A8%EA%BB%98%ED%95%98%EB%8A%94-Live-Study-9%EC%A3%BC%EC%B0%A8-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)
